# Site settings
title: Roll Counter
email: ux@jvlia.co
description: > # this means to ignore newlines until "baseurl:"
 Track and graph die rolls.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dice.jvlia.co" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
