# Site settings
title: Dice Counter
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 A thing to keep track of dice rolls.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dice.jvlia.co" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
